# src/commit/commit_to_github.py
import os
import shutil
import logging
import time
from pathlib import Path
from datetime import datetime
from git import Repo
from github import Github
from dotenv import load_dotenv

load_dotenv()
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = os.getenv("GITHUB_REPO", "areebaahmad123/mlops-autopilot")
BRANCH_NAME = f"mlops-fix-{datetime.now().strftime('%Y%m%d')}"

def main(fixes_dir: str = "fixes", target_repo_dir: str = "target_repo"):
    if not GITHUB_TOKEN:
        raise ValueError("GITHUB_TOKEN not set in .env")

    fixes_path = Path(fixes_dir).resolve()
    repo_path = Path(target_repo_dir).resolve()

    if not fixes_path.exists():
        logger.error(f"Fixes directory not found: {fixes_path}")
        return

    # --- FORCE DELETE ---
    if repo_path.exists():
        logger.info("Deleting old target_repo...")
        shutil.rmtree(repo_path, ignore_errors=True)
        time.sleep(1)

    # --- CLONE ---
    logger.info(f"Cloning {GITHUB_REPO}...")
    repo_url = f"https://{GITHUB_TOKEN}@github.com/{GITHUB_REPO}.git"
    repo = Repo.clone_from(repo_url, repo_path)

    # --- BRANCH ---
    if BRANCH_NAME not in [h.name for h in repo.heads]:
        repo.git.checkout('-b', BRANCH_NAME)
    else:
        repo.heads[BRANCH_NAME].checkout()

    # --- COPY & VERIFY ---
    copied_files = []
    for src in fixes_path.rglob("*"):
        if not src.is_file():
            continue
        rel = src.relative_to(fixes_path)
        dst = repo_path / rel
        dst.parent.mkdir(parents=True, exist_ok=True)

        try:
            shutil.copy2(src, dst)
            if dst.exists() and dst.stat().st_size > 0:
                copied_files.append(dst)
                logger.info(f"Copied: {rel}")
            else:
                logger.error(f"Copy failed (empty): {dst}")
        except Exception as e:
            logger.error(f"Copy failed: {src} → {dst} | {e}")

    if not copied_files:
        logger.error("No files copied successfully!")
        return

    # --- ADD TO GIT ---
    try:
        repo.index.add([str(f) for f in copied_files])
        logger.info(f"Added {len(copied_files)} files to Git")
    except Exception as e:
        logger.error(f"Git add failed: {e}")
        return

    # --- COMMIT ---
    repo.index.commit(
        f"chore: MLOps Autopilot fixes ({len(copied_files)} files)\n\n"
        "AI-generated: Dockerfile, mlflow.yaml, tests"
    )
    logger.info("Committed")

    # --- PUSH ---
    origin = repo.remote("origin")
    origin.push(refspec=f"{BRANCH_NAME}:{BRANCH_NAME}", force=True)
    logger.info(f"Pushed {BRANCH_NAME}")

    # --- GITHUB CLIENT ---
    gh = Github(GITHUB_TOKEN)
    repo_gh = gh.get_repo(GITHUB_REPO)

    # --- PR: Reuse if exists ---
    existing_prs = repo_gh.get_pulls(state='open', head=f"{repo_gh.owner.login}:{BRANCH_NAME}")
    if existing_prs.totalCount > 0:
        pr = existing_prs[0]
        logger.info(f"PR already exists: {pr.html_url}")
    else:
        pr = repo_gh.create_pull(
            title="MLOps Autopilot: Add Dockerfile, MLflow, Tests",
            body="""**Auto-generated by MLOps Autopilot Auditor**

**Fixes Added:**
- `Dockerfile`
- `mlflow.yaml`
- `tests/test_example.py`

**Audit → AI Fix → Auto-PR**  
Closes #1
""",
            head=BRANCH_NAME,
            base="main"
        )
        logger.info(f"PR CREATED: {pr.html_url}")

if __name__ == "__main__":
    import sys
    main(*sys.argv[1:])