import json
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import joblib
from datetime import datetime
import os
import subprocess

# Load agent plan from file (generated by agent_runner.py)
def load_agent_plan():
    plan_file = "agent/plan.json"
    if os.path.exists(plan_file):
        with open(plan_file, "r") as f:
            return json.load(f)
    else:
        print("Warning: plan.json not found. Using hardcoded plan.")
        return {
            "task": "binary_classification",
            "model": "LogisticRegression",
            "features": ["age", "income"],
            "target": "purchased",
            "hyperparams": {"C": 1.0}
        }

# Load dataset
def load_data():
    df = pd.read_csv("src/data/sample_dataset.csv")
    print(f"Data loaded: {df.shape[0]} rows, {df.shape[1]} columns")
    return df

# Train model
def train_model(df, plan):
    X = df[plan["features"]]
    y = df[plan["target"]]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    model = LogisticRegression(**plan["hyperparams"])
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    
    return model, accuracy

# Save model and logs
def save_results(model, accuracy, plan):
    os.makedirs("models", exist_ok=True)
    joblib.dump(model, "models/model.pkl")
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = (
        f"## Training Run: {timestamp}\n"
        f"- **Task**: {plan['task']}\n"
        f"- **Model**: {plan['model']}\n"
        f"- **Features**: {', '.join(plan['features'])}\n"
        f"- **Target**: {plan['target']}\n"
        f"- **Hyperparams**: {plan['hyperparams']}\n"
        f"- **Accuracy**: {accuracy:.4f}\n\n"
    )
    
    with open("docs/TRAINING_LOGS.md", "a") as f:
        f.write(log_entry)
    
    print(f"Model saved → models/model.pkl")
    print(f"Log updated → docs/TRAINING_LOGS.md")

# Auto GitHub PR (via CLI)
def create_pr():
    try:
        subprocess.run(["git", "config", "--global", "user.email", "you@example.com"], check=True)
        subprocess.run(["git", "config", "--global", "user.name", "MLOps AutoPilot"], check=True)
        subprocess.run(["git", "add", "."], check=True)
        subprocess.run(["git", "commit", "-m", "chore: auto-train model with agent plan"], check=True)
        subprocess.run(["git", "push"], check=True)
        print("Changes pushed to GitHub!")
    except Exception as e:
        print(f"Git push failed: {e}")

if __name__ == "__main__":
    print("Starting MLOps AutoPilot Training...\n")
    
    plan = load_agent_plan()
    df = load_data()
    model, accuracy = train_model(df, plan)
    save_results(model, accuracy, plan)
    create_pr()
    
    print(f"\nTraining Complete! Accuracy: {accuracy:.4f}")
    print("Next: Trigger n8n webhook → Phase 5")